apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  .env: |
      "host": "0.0.0.0"
      "port": "8080"
      "expiration_duration": 0.5
      "db_hostname": 'mysql.default.svc.cluster.local'


