apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: db_password
        ports:
        - containerPort: 3306
          name: db-container
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
          - name: mysql-initdb
            mountPath: /docker-entrypoint-initdb.d/initdb.sql
            subPath: initdb.sql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: pvcmysql
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE secretnotes;
    use secretnotes;

    CREATE TABLE notes (
      id INT AUTO_INCREMENT PRIMARY KEY,
      content VARCHAR(1000),
      creation_time DateTime DEFAULT CURRENT_TIMESTAMP,
      expiration_time DateTime default CURRENT_TIMESTAMP
    );