apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: secretnotes
          image: secretnotes:5
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: db_password
            - name: DB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: db_username
          volumeMounts:
            - mountPath: /env/.env
              subPath: .env
              name: config-map
              readOnly: true
      volumes:
        - name: config-map
          configMap:
            name: config-map