version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_ROOT_USERNAME: "root"
      DB_ROOT_PASSWORD: "root"
    volumes:
      - PATH_TO_app/config/config.yaml:/env/.env:ro

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

